//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TirleaPaul2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Orders_21
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public int CategoryID { get; set; }
        public string CategoryName { get; set; }
        public string Description { get; set; }
        public Nullable<short> UnitsInStock { get; set; }
        public decimal UnitPrice { get; set; }
        public short Quantity { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<int> OrderYear { get; set; }
        public Nullable<int> ShippedYear { get; set; }
    }
}
