//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TirleaPaul2022
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Sales_Value
    {
        public int EmployeeID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public int OrderID { get; set; }
        public Nullable<int> OrderYear { get; set; }
        public Nullable<decimal> OrderValue { get; set; }
    }
}
